name: Upload Java Nightly builds

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: Job prefix to use.
        required: false
        default: ''

jobs:
  upload:
    env:
      PREFIX: ${{ github.event.inputs.prefix || ''}}
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout Arrow
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 1
#           path: arrow
#           repository: apache/arrow
#           ref: master
#           submodules: recursive
#       - name: Checkout Crossbow
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           path: crossbow
#           repository: ursacomputing/crossbow
#           ref: master 
#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           cache: 'pip'
#           python-version: 3.8
#       - name: Install Archery
#         shell: bash
#         run: pip install -e arrow/dev/archery[all]
      - run: mkdir -p binaries
      - name: Download Artifacts
        run: |
          if [ -z $PREFIX ]; then
            PREFIX=nightly-packaging-$(date +%Y-%m-%d)-0
          fi
          echo $PREFIX
          # archery crossbow download-artifacts -f java-jars -t binaries $PREFIX
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-java-root-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-format-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-format-9.0.0.dev174.jar
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-vector-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-vector-9.0.0.dev174.jar
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-memory-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-memory-core-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-memory-netty-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-memory-core-9.0.0.dev174.jar
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-memory-netty-9.0.0.dev174.jar
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/arrow-flight-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/flight-core-9.0.0.dev174.pom
          wget https://github.com/ursacomputing/crossbow/releases/download/nightly-packaging-2022-06-06-0-github-java-jars/flight-core-9.0.0.dev174.jar
          mv *.pom binaries
          mv *.jar binaries
          tree binaries
          if [ -n "$(ls -A binaries/*/*/)" ]; then
            echo "Found files!"
            echo "GOT_FILES=true" >> $GITHUB_ENV
          else
            echo "No files found. Stopping upload."
            echo "GOT_FILES=false" >> $GITHUB_ENV
          fi
          
